brand: LazyDaddy
developer: LazyDaddy
email: ocxeverywhere@gmail.com
support_url: https://ko-fi.com/W4I222SBAF
business:
  registration: 426-19-02556
  address_ko: 대전광역시 동구 다복1길 11
  address_en: 11, Dabok 1-gil, Dong-gu, Daejeon, Republic of Korea
